/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/conference-room.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0.02, 3.09, -1.85]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Mesh35_wood_panel_3_44_1_Group004_Model004.geometry}
          material={nodes.Mesh35_wood_panel_3_44_1_Group004_Model004.material}
        />
        <mesh
          geometry={nodes.Mesh35_wood_panel_3_44_1_Group004_Model004_1.geometry}
          material={nodes.Mesh35_wood_panel_3_44_1_Group004_Model004_1.material}
        />
      </group>
      <group position={[1.75, 0.33, -3.01]} rotation={[Math.PI / 2, 0, 1.48]}>
        <mesh
          geometry={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_1.geometry}
          material={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_1.material}
        />
        <mesh
          geometry={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_2.geometry}
          material={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_2.material}
        />
        <mesh
          geometry={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_3.geometry}
          material={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_3.material}
        />
        <mesh
          geometry={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_4.geometry}
          material={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_4.material}
        />
      </group>
      <group position={[5.62, 0.33, -3.07]} rotation={[Math.PI / 2, 0, -2.01]}>
        <mesh
          geometry={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_1.geometry}
          material={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_1.material}
        />
        <mesh
          geometry={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_2.geometry}
          material={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_2.material}
        />
        <mesh
          geometry={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_3.geometry}
          material={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_3.material}
        />
        <mesh
          geometry={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_4.geometry}
          material={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_4.material}
        />
      </group>
      <group position={[4.77, 0.33, -4]} rotation={[Math.PI / 2, 0, -Math.PI]}>
        <mesh
          geometry={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_1.geometry}
          material={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_1.material}
        />
        <mesh
          geometry={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_2.geometry}
          material={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_2.material}
        />
        <mesh
          geometry={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_3.geometry}
          material={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_3.material}
        />
        <mesh
          geometry={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_4.geometry}
          material={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_4.material}
        />
      </group>
      <group position={[4.04, 0.33, -4]} rotation={[Math.PI / 2, 0, -Math.PI]}>
        <mesh
          geometry={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_1.geometry}
          material={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_1.material}
        />
        <mesh
          geometry={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_2.geometry}
          material={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_2.material}
        />
        <mesh
          geometry={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_3.geometry}
          material={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_3.material}
        />
        <mesh
          geometry={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_4.geometry}
          material={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_4.material}
        />
      </group>
      <group position={[3.3, 0.33, -4]} rotation={[Math.PI / 2, 0, -Math.PI]}>
        <mesh
          geometry={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_1.geometry}
          material={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_1.material}
        />
        <mesh
          geometry={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_2.geometry}
          material={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_2.material}
        />
        <mesh
          geometry={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_3.geometry}
          material={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_3.material}
        />
        <mesh
          geometry={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_4.geometry}
          material={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_4.material}
        />
      </group>
      <group position={[2.57, 0.33, -4]} rotation={[Math.PI / 2, 0, -Math.PI]}>
        <mesh
          geometry={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_1.geometry}
          material={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_1.material}
        />
        <mesh
          geometry={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_2.geometry}
          material={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_2.material}
        />
        <mesh
          geometry={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_3.geometry}
          material={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_3.material}
        />
        <mesh
          geometry={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_4.geometry}
          material={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_4.material}
        />
      </group>
      <group position={[4.78, 0.33, -2.1]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_1.geometry}
          material={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_1.material}
        />
        <mesh
          geometry={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_2.geometry}
          material={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_2.material}
        />
        <mesh
          geometry={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_3.geometry}
          material={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_3.material}
        />
        <mesh
          geometry={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_4.geometry}
          material={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_4.material}
        />
      </group>
      <group position={[4.05, 0.33, -2.1]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_1.geometry}
          material={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_1.material}
        />
        <mesh
          geometry={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_2.geometry}
          material={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_2.material}
        />
        <mesh
          geometry={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_3.geometry}
          material={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_3.material}
        />
        <mesh
          geometry={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_4.geometry}
          material={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_4.material}
        />
      </group>
      <group position={[3.31, 0.33, -2.1]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_1.geometry}
          material={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_1.material}
        />
        <mesh
          geometry={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_2.geometry}
          material={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_2.material}
        />
        <mesh
          geometry={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_3.geometry}
          material={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_3.material}
        />
        <mesh
          geometry={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_4.geometry}
          material={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_4.material}
        />
      </group>
      <group position={[2.57, 0.33, -2.1]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_1.geometry}
          material={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_1.material}
        />
        <mesh
          geometry={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_2.geometry}
          material={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_2.material}
        />
        <mesh
          geometry={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_3.geometry}
          material={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_3.material}
        />
        <mesh
          geometry={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_4.geometry}
          material={nodes.Mesh710_Group57_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop_4.material}
        />
      </group>
      <group position={[1.2, 0, 4.6]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Mesh651_Group244_Model002_1.geometry} material={materials.PIEDRA002} />
        <mesh geometry={nodes.Mesh651_Group244_Model002_2.geometry} material={materials._Charcoal_} />
      </group>
      <group position={[-0.18, 0, 0.18]} rotation={[-Math.PI, -Math.PI / 2, 0]} scale={[-0.14, -0.11, -0.11]}>
        <mesh
          geometry={nodes.eb_FOLDING_1_X_3_GLASS_eb_FOLDING_1_X_3_GLASS_321294_Defi007.geometry}
          material={materials['[Color_E14]1']}
        />
        <mesh
          geometry={nodes.eb_FOLDING_1_X_3_GLASS_eb_FOLDING_1_X_3_GLASS_321294_Defi007_1.geometry}
          material={materials.eb_GLAZING1}
        />
        <mesh
          geometry={nodes.eb_FOLDING_1_X_3_GLASS_eb_FOLDING_1_X_3_GLASS_321294_Defi007_2.geometry}
          material={materials.Generic1}
        />
        <mesh
          geometry={nodes.eb_FOLDING_1_X_3_GLASS_eb_FOLDING_1_X_3_GLASS_321294_Defi007_3.geometry}
          material={materials.eb_HANDLE1}
        />
        <mesh
          geometry={nodes.eb_FOLDING_1_X_3_GLASS_eb_FOLDING_1_X_3_GLASS_321294_Defi007_4.geometry}
          material={materials.Color_E14}
        />
        <mesh
          geometry={nodes.eb_FOLDING_1_X_3_GLASS_eb_FOLDING_1_X_3_GLASS_321294_Defi007_5.geometry}
          material={materials.eb_HARDWARE1}
        />
      </group>
      <mesh
        geometry={nodes.Mesh1151_ground_005_1_Group186_VASO_11_1_1_Model.geometry}
        material={nodes.Mesh1151_ground_005_1_Group186_VASO_11_1_1_Model.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Mesh1055_pot_005_1_Group186_VASO_11_1_1_Model.geometry}
        material={nodes.Mesh1055_pot_005_1_Group186_VASO_11_1_1_Model.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Mesh1054_ground_005_Group185_VASO_11_1_Model.geometry}
        material={nodes.Mesh1054_ground_005_Group185_VASO_11_1_Model.material}
        position={[-0.06, 0, -0.15]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Mesh1031_Plant_005_Group185_VASO_11_1_Model.geometry}
        material={materials['Material__1.001']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Mesh964_Plant_005_Group185_VASO_11_1_Model.geometry}
        material={materials.M_13___Default1}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Mesh958_pot_005_Group185_VASO_11_1_Model.geometry}
        material={nodes.Mesh958_pot_005_Group185_VASO_11_1_Model.material}
        position={[-0.06, 0, -0.15]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Mesh728_Group62_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop.geometry}
        material={nodes.Mesh728_Group62_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Mesh727_Group62_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop.geometry}
        material={nodes.Mesh727_Group62_SPG_22_5_3D_dwg_2_3_Haworth_Immerse_table___Pop.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Mesh646_Component_1_1_Haworth_Immerse_table___Poppy_chair1_Mode.geometry}
        material={nodes.Mesh646_Component_1_1_Haworth_Immerse_table___Poppy_chair1_Mode.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Mesh645_Group24_Haworth_Immerse_table___Poppy_chair1_Model.geometry}
        material={materials.white1}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Mesh635_Group23_Haworth_Immerse_table___Poppy_chair1_Model.geometry}
        material={nodes.Mesh635_Group23_Haworth_Immerse_table___Poppy_chair1_Model.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Mesh630_Component_2_3_Group22_Group_82_1_Model.geometry}
        material={nodes.Mesh630_Component_2_3_Group22_Group_82_1_Model.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Mesh282_Difference13_Group21_Group_82_1_Model.geometry}
        material={nodes.Mesh282_Difference13_Group21_Group_82_1_Model.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Mesh87_Group20_Group_82_1_Model.geometry}
        material={materials.Color_A16}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <group position={[-0.05, 0.17, 0]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Mesh35_wood_panel_3_44_1_Group004_Model_1.geometry}
          material={nodes.Mesh35_wood_panel_3_44_1_Group004_Model_1.material}
        />
        <mesh
          geometry={nodes.Mesh35_wood_panel_3_44_1_Group004_Model_2.geometry}
          material={nodes.Mesh35_wood_panel_3_44_1_Group004_Model_2.material}
        />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Mesh22_Group16_Model_1.geometry} material={nodes.Mesh22_Group16_Model_1.material} />
        <mesh geometry={nodes.Mesh22_Group16_Model_2.geometry} material={materials.Material} />
      </group>
      <mesh
        geometry={nodes.Mesh21_kuzco_wire4_Group16_Model.geometry}
        material={nodes.Mesh21_kuzco_wire4_Group16_Model.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Mesh17_Group18_Group16_Model.geometry}
        material={nodes.Mesh17_Group18_Group16_Model.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Mesh16_Group19_Group18_Group16_Model.geometry}
        material={nodes.Mesh16_Group19_Group18_Group16_Model.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Mesh15_Group17_Group16_Model.geometry}
        material={materials.LIGHT_Bulb2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Mesh14_Group15_Model.geometry}
        material={materials.Chocofur_Concrete_Solid_07}
        position={[-0.06, 0, -0.15]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <group position={[0.1, 1.56, -3.12]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Mesh13_Group4_Group3_Model_1.geometry}
          material={nodes.Mesh13_Group4_Group3_Model_1.material}
        />
        <mesh
          geometry={nodes.Mesh13_Group4_Group3_Model_2.geometry}
          material={nodes.Mesh13_Group4_Group3_Model_2.material}
        />
      </group>
      <mesh
        geometry={nodes.Mesh3_Group5_Group4_Group3_Model.geometry}
        material={materials['_4.001']}
        position={[0.05, 1.29, -3.09]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <group position={[0.2, 0.49, -3.05]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Mesh2_Group1_Model_1.geometry} material={materials._0136_Charcoal_1} />
        <mesh geometry={nodes.Mesh2_Group1_Model_2.geometry} material={nodes.Mesh2_Group1_Model_2.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/conference-room.gltf')
